### ISSUE TITLE
Missing configuration documentation

### ISSUE THREAD

**Issue by Alessia958** [adrien2p/nestjs-dialogflow#2]
## I'm submitting a

[ ] Regression
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request

I was trying to get your sample application run on heroku(I also tried locally, of course) but I still get a 500 with message "Missing authentication header".
I obviously set the environment variable DIALOG_FLOW_AUTHORIZATION_TOKEN, as you said to your documentation, equal to my client token (I also tried developer token) of dialog flow.

What am I missing?
I'm not sure it's a problem with this library or the configuration of my dialogflow project.

**Comment by adrien2p** [comment]
Hey, i think you forgot to set the Authorization header in your dialogFlow console as the following exemple

<img width="816" alt="screen shot 2018-10-29 at 17 18 27" src="https://user-images.githubusercontent.com/25098370/47664188-d59dbb80-db9e-11e8-8b53-43006f3ac0c2.png">
