### ISSUE TITLE
Interfaces do not match the latest DF documentation

### ISSUE THREAD

**Issue by tgwesleyclover** [adrien2p/nestjs-dialogflow#45]
Interface no longer matches the DF official documentation. The output contexts should be an array, instead it's just a single object. 

Interface: DialogFlowResponse
Location: node_modules/nestjs-dialogflow/lib/interfaces/dialog-flow-response.interface.d.ts
Problem: QueryResult.outputContexts: OutputContexts 
Solution: QueryResult.outputContexts: OutputContexts[]

Doc ref: https://cloud.google.com/dialogflow/es/docs/reference/rpc/google.cloud.dialogflow.v2#webhookresponse

**Comment by adrien2p** [comment]
Hi there,

I am open for pr if needed
